### ISSUE TITLE
[Feature request] Access to colors as normal environment variables

### ISSUE THREAD

**Issue by 241m** [base16-project/base16-shell#13]
Hello! First of, glad to see the Base16 project is up and active :)

I just want access to my color scheme as environment variables, e.g. `$color1`, `$color2`, etc. It seems the template scripts unset these variables.

What's the best way to do this?

**Comment by JamyGolden** [comment]
Hello :smile: What are you trying to do with this? 

I'm wondering because if it's a good reason and the best way to do it is to expose the variables (I think there's probably an alternative to this), then we can consider exposing them.

**Comment by 241m** [comment]
For terminal emulators and code editors, or apps with complex theming, I'll clone its specific base16 repo (i.e. bae16-vim, base16-rofi, etc.) if it exists, which is fine.

But for certain types of small-ish programs, I think it's neater to just have a single repo, base16-shell (or base16-schemes?), and assign colors manually via shell scripts / aliases or config file. Because:

1. I'm usually using just a few colors, not an entire scheme:

```shell
dmenu_run -nb "$COLOR00" -sb "$COLOR04"
```
```ini
[colors]
foreground = ${env:COLOR04}
background = ${env:COLOR00}
```
And if the program's config file doesn't allow env vars, I'm fine with copy+pasting it manually.

2. When I'm in a _"ricing"_ mindset, I tend to switch up and try out new programs, which might not have base16 templates. This makes it easier apply themes ad-hoc.

I acknowledge that this is just my personal way of doing things. Exposing the variables might be the simplest, non-invasive way to allow this that I can think of.

**Comment by JamyGolden** [comment]
Thanks! I've created a PR for (link above). Have a look at it and if there is something you think should be changed before it's merged then leave a comment :)
