### ISSUE TITLE
[Bug report] color test doesn't respect $BASE16_THEME

### ISSUE THREAD

**Issue by mahmoudhossam** [base16-project/base16-shell#43]
## Describe the bug

The color test script doesn't use the existing theme and reverts to default

## Expected behavior

colortest should use the theme set by the user instead of changing it to the default dark theme

## **System**

**Operating system:** MacOS Sonoma 14.2

**Terminal:** iTerm2

**Comment by JamyGolden** [comment]
This should now be solved after merging https://github.com/tinted-theming/base16-shell/pull/48. Can you check if it's fixed for you?

**Comment by mahmoudhossam** [comment]
> This should now be solved after merging #48. Can you check if it's fixed for you?

It is, thank you very much.
