### ISSUE TITLE
[Bug report] Last commit adding Sublime Merge hooks breaks everything if that plugin is not installed

### ISSUE THREAD

**Issue by acidghost** [base16-project/base16-shell#45]
## Describe the bug

The hooks should not use `exit` because they're `source`d: https://github.com/tinted-theming/base16-shell/blob/98078ba1261b28b1eb36e1c6d219c20f5d4e4c65/hooks/base16-sublime-merge.sh#L7-L9

Using `exit` makes the shell exit immediately.

## Expected behavior

Use `return` to not quit the shell.

## **System**

**Operating system:** unix

**Terminal:** any

**Comment by jgb** [comment]
I can confirm this bug, and that the linked PR fixes the problem.

**Comment by JamyGolden** [comment]
Thanks for reporting, this was closed around the time this issue was created: https://github.com/tinted-theming/base16-shell/pull/44
